create table File_Extensions_To_Export (Output_Directory text, File_Extension text);

insert into File_Extensions_To_Export values ('Documents','doc');
insert into File_Extensions_To_Export values ('Documents','docx');
insert into File_Extensions_To_Export values ('Documents','odt');
insert into File_Extensions_To_Export values ('Spreadsheets','csv');
insert into File_Extensions_To_Export values ('Spreadsheets','xls');
insert into File_Extensions_To_Export values ('Spreadsheets','xlsx');
insert into File_Extensions_To_Export values ('Spreadsheets','ods');
insert into File_Extensions_To_Export values ('Text','rtf');
insert into File_Extensions_To_Export values ('Text','txt');
insert into File_Extensions_To_Export values ('Presentation','ppt');
insert into File_Extensions_To_Export values ('Presentation','pptx');
insert into File_Extensions_To_Export values ('Presentation','sxi');
insert into File_Extensions_To_Export values ('Mail','pst');
insert into File_Extensions_To_Export values ('Mail','ost');
insert into File_Extensions_To_Export values ('Mail','edb');
insert into File_Extensions_To_Export values ('Mail','mbx');
insert into File_Extensions_To_Export values ('Mail','eml');
insert into File_Extensions_To_Export values ('Mail','emlx');
insert into File_Extensions_To_Export values ('Mail','idx');
insert into File_Extensions_To_Export values ('Mail','dbx');
insert into File_Extensions_To_Export values ('Mail','msg');
insert into File_Extensions_To_Export values ('PDF','pdf');
insert into File_Extensions_To_Export values ('Pics','jpg');
insert into File_Extensions_To_Export values ('Pics','jpeg');
insert into File_Extensions_To_Export values ('Pics','bmp');
insert into File_Extensions_To_Export values ('Pics','gif');
insert into File_Extensions_To_Export values ('Pics','png');
insert into File_Extensions_To_Export values ('Pics','tif');
insert into File_Extensions_To_Export values ('Pics','tiff');
insert into File_Extensions_To_Export values ('Quickbooks','qbb');
insert into File_Extensions_To_Export values ('Quickbooks','qbw');
insert into File_Extensions_To_Export values ('Quickbooks','qb2016');
insert into File_Extensions_To_Export values ('Quickbooks','qb2015');
insert into File_Extensions_To_Export values ('Quickbooks','qb2014');
insert into File_Extensions_To_Export values ('Quickbooks','qbmb');
insert into File_Extensions_To_Export values ('Quickent','qdf');
insert into File_Extensions_To_Export values ('Database Files','db');
insert into File_Extensions_To_Export values ('Database Files','mdf');
insert into File_Extensions_To_Export values ('Database Files','ldf');
insert into File_Extensions_To_Export values ('Database Files','mdb');
insert into File_Extensions_To_Export values ('Database Files','sqlite');
insert into File_Extensions_To_Export values ('Database Files','sqlite3');
insert into File_Extensions_To_Export values ('Archive','7z');
insert into File_Extensions_To_Export values ('Archive','tar');
insert into File_Extensions_To_Export values ('Archive','zip');
insert into File_Extensions_To_Export values ('Archive','gzip');
insert into File_Extensions_To_Export values ('Archive','rar');

